services:
  inflitrix-webapp:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - inflitrix-model
  inflitrix-model:
    build:
      context: ./model
    ports:
      - 8000:8000
